import http from 'node:http';
import { Pool } from 'pg';

const pool = new Pool({ connectionString: process.env.DATABASE_URL || 'postgres://road:road@localhost:5432/road' });
const port = Number(process.env.PORT || 3001);
const statuses = new Set(['waiting', 'todo', 'done', 'cancelled']);
const uuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const datePattern = /^\d{4}-\d{2}-\d{2}$/;

async function init() {
  await pool.query(`
    CREATE EXTENSION IF NOT EXISTS pgcrypto;
    CREATE TABLE IF NOT EXISTS nodes (
      id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
      title text NOT NULL DEFAULT '',
      status text NOT NULL DEFAULT 'todo' CHECK (status IN ('waiting','todo','done','cancelled')),
      event_date date,
      created_at timestamptz NOT NULL DEFAULT now(),
      updated_at timestamptz NOT NULL DEFAULT now()
    );
    CREATE TABLE IF NOT EXISTS sections (
      id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
      number bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
      name text,
      created_at timestamptz NOT NULL DEFAULT now()
    );
    ALTER TABLE nodes ADD COLUMN IF NOT EXISTS section_id uuid REFERENCES sections(id) ON DELETE SET NULL;
    CREATE TABLE IF NOT EXISTS links (
      id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
      source_id uuid NOT NULL REFERENCES nodes(id) ON DELETE CASCADE,
      target_id uuid NOT NULL REFERENCES nodes(id) ON DELETE CASCADE,
      order_index integer NOT NULL DEFAULT 0,
      created_at timestamptz NOT NULL DEFAULT now(),
      UNIQUE(source_id, target_id),
      CHECK(source_id <> target_id)
    );
    CREATE INDEX IF NOT EXISTS links_source_idx ON links(source_id, order_index);
    CREATE INDEX IF NOT EXISTS links_target_idx ON links(target_id);
    CREATE INDEX IF NOT EXISTS nodes_section_idx ON nodes(section_id);
  `);
  const client = await pool.connect();
  try {
    await client.query('BEGIN');
    await client.query('SELECT pg_advisory_xact_lock(8675309)');
    await reconcileSections(client);
    await client.query('COMMIT');
  } catch (error) { await client.query('ROLLBACK'); throw error; }
  finally { client.release(); }
}

async function reconcileSections(client) {
  const nodeResult = await client.query('SELECT id, section_id FROM nodes ORDER BY created_at, id');
  const linkResult = await client.query('SELECT source_id, target_id FROM links');
  const sectionResult = await client.query('SELECT id, number, name FROM sections');
  const nodes = nodeResult.rows;
  const adjacency = new Map(nodes.map(node => [node.id, []]));
  for (const link of linkResult.rows) {
    adjacency.get(link.source_id)?.push(link.target_id);
    adjacency.get(link.target_id)?.push(link.source_id);
  }
  const byId = new Map(nodes.map(node => [node.id, node]));
  const sections = new Map(sectionResult.rows.map(section => [section.id, section]));
  const claimed = new Set();
  const visited = new Set();
  const isolated = [];
  for (const node of nodes) {
    if (visited.has(node.id)) continue;
    const component = [];
    const stack = [node.id];
    visited.add(node.id);
    while (stack.length) {
      const id = stack.pop();
      component.push(byId.get(id));
      for (const neighbor of adjacency.get(id) || []) if (!visited.has(neighbor)) { visited.add(neighbor); stack.push(neighbor); }
    }
    if (component.length === 1) { if (node.section_id) isolated.push(node.id); continue; }
    const candidates = [...new Set(component.map(item => item.section_id).filter(Boolean))]
      .map(id => sections.get(id)).filter(section => section && !claimed.has(section.id))
      .sort((a, b) => Number(Boolean(b.name)) - Number(Boolean(a.name)) || Number(a.number) - Number(b.number));
    let sectionId = candidates[0]?.id;
    if (!sectionId) {
      const created = await client.query('INSERT INTO sections DEFAULT VALUES RETURNING id');
      sectionId = created.rows[0].id;
    }
    claimed.add(sectionId);
    await client.query('UPDATE nodes SET section_id=$1 WHERE id = ANY($2::uuid[]) AND section_id IS DISTINCT FROM $1', [sectionId, component.map(item => item.id)]);
  }
  if (isolated.length) await client.query('UPDATE nodes SET section_id=NULL WHERE id = ANY($1::uuid[])', [isolated]);
  await client.query('DELETE FROM sections WHERE id NOT IN (SELECT DISTINCT section_id FROM nodes WHERE section_id IS NOT NULL)');
}

function send(res, code, data) {
  res.writeHead(code, { 'Content-Type': 'application/json; charset=utf-8', 'Access-Control-Allow-Origin': process.env.CORS_ORIGIN || '*', 'Access-Control-Allow-Methods': 'GET,POST,PATCH,DELETE,OPTIONS', 'Access-Control-Allow-Headers': 'Content-Type' });
  res.end(JSON.stringify(data));
}

async function body(req) {
  let raw = '';
  for await (const chunk of req) {
    raw += chunk;
    if (raw.length > 65536) throw Object.assign(new Error('Слишком большой запрос'), { code: 413 });
  }
  try { return raw ? JSON.parse(raw) : {}; }
  catch { throw Object.assign(new Error('Некорректный JSON'), { code: 400 }); }
}

function nodeValues(input, partial = false) {
  if (!input || typeof input !== 'object' || Array.isArray(input)) throw Object.assign(new Error('Нужен объект задачи'), { code: 400 });
  const out = {};
  if ('title' in input) {
    if (typeof input.title !== 'string' || input.title.length > 500) throw Object.assign(new Error('Название должно быть строкой до 500 символов'), { code: 400 });
    out.title = input.title;
  }
  if ('status' in input) {
    if (!statuses.has(input.status)) throw Object.assign(new Error('Неизвестный статус'), { code: 400 });
    out.status = input.status;
  }
  if ('eventDate' in input) {
    if (input.eventDate !== null && (typeof input.eventDate !== 'string' || !datePattern.test(input.eventDate) || Number.isNaN(Date.parse(input.eventDate)) || new Date(input.eventDate).toISOString().slice(0, 10) !== input.eventDate)) throw Object.assign(new Error('Дата должна быть в формате YYYY-MM-DD'), { code: 400 });
    out.event_date = input.eventDate;
  }
  if (partial && Object.keys(out).length === 0) throw Object.assign(new Error('Нет полей для обновления'), { code: 400 });
  return out;
}

function mapNode(row) { return { id: row.id, title: row.title, status: row.status, eventDate: row.event_date ? (row.event_date instanceof Date ? row.event_date.toISOString() : String(row.event_date)).slice(0, 10) : null, createdAt: row.created_at, updatedAt: row.updated_at, sectionId: row.section_id }; }
function mapLink(row) { return { id: row.id, sourceId: row.source_id, targetId: row.target_id, order: row.order_index }; }
function mapSection(row) { return { id: row.id, number: Number(row.number), name: row.name }; }

async function route(req, res) {
  if (req.method === 'OPTIONS') return send(res, 204, null);
  const path = new URL(req.url, 'http://localhost').pathname;
  if (req.method === 'GET' && path === '/api/health') return send(res, 200, { ok: true });
  if (req.method === 'GET' && path === '/api/graph') {
    const [nodes, links, sections] = await Promise.all([
      pool.query('SELECT * FROM nodes ORDER BY created_at, id'),
      pool.query('SELECT * FROM links ORDER BY source_id, order_index, created_at, id'),
      pool.query('SELECT * FROM sections ORDER BY number')
    ]);
    return send(res, 200, { nodes: nodes.rows.map(mapNode), links: links.rows.map(mapLink), sections: sections.rows.map(mapSection) });
  }
  if (req.method === 'POST' && path === '/api/nodes') {
    const values = nodeValues(await body(req));
    const keys = Object.keys(values);
    const result = keys.length
      ? await pool.query(`INSERT INTO nodes (${keys.join(',')}) VALUES (${keys.map((_, i) => `$${i + 1}`).join(',')}) RETURNING *`, Object.values(values))
      : await pool.query('INSERT INTO nodes DEFAULT VALUES RETURNING *');
    return send(res, 201, mapNode(result.rows[0]));
  }
  const nodeMatch = path.match(/^\/api\/nodes\/([^/]+)$/);
  if (nodeMatch && uuid.test(nodeMatch[1])) {
    const id = nodeMatch[1];
    if (req.method === 'PATCH') {
      const values = nodeValues(await body(req), true);
      const keys = Object.keys(values);
      const result = await pool.query(`UPDATE nodes SET ${keys.map((key, i) => `${key}=$${i + 1}`).join(',')}, updated_at=now() WHERE id=$${keys.length + 1} RETURNING *`, [...Object.values(values), id]);
      return result.rowCount ? send(res, 200, mapNode(result.rows[0])) : send(res, 404, { error: 'Задача не найдена' });
    }
    if (req.method === 'DELETE') {
      const client = await pool.connect();
      try {
        await client.query('BEGIN');
        await client.query('SELECT pg_advisory_xact_lock(8675309)');
        const result = await client.query('DELETE FROM nodes WHERE id=$1', [id]);
        if (result.rowCount) await reconcileSections(client);
        await client.query('COMMIT');
        return send(res, result.rowCount ? 200 : 404, result.rowCount ? { deleted: true } : { error: 'Задача не найдена' });
      } catch (error) { await client.query('ROLLBACK'); throw error; }
      finally { client.release(); }
    }
  }
  if (req.method === 'POST' && path === '/api/links') {
    const input = await body(req);
    if (!uuid.test(input.sourceId || '') || !uuid.test(input.targetId || '') || input.sourceId === input.targetId) return send(res, 400, { error: 'Укажите два разных квадрата' });
    const client = await pool.connect();
    try {
      await client.query('BEGIN');
      await client.query('SELECT pg_advisory_xact_lock(8675309)');
      const exists = await client.query('SELECT id FROM nodes WHERE id = ANY($1::uuid[])', [[input.sourceId, input.targetId]]);
      if (exists.rowCount !== 2) { await client.query('ROLLBACK'); return send(res, 404, { error: 'Квадрат не найден' }); }
      const cycle = await client.query(`WITH RECURSIVE descendants(id) AS (
        SELECT target_id FROM links WHERE source_id=$1
        UNION SELECT links.target_id FROM links JOIN descendants ON links.source_id=descendants.id
      ) SELECT 1 FROM descendants WHERE id=$2 LIMIT 1`, [input.targetId, input.sourceId]);
      if (cycle.rowCount) { await client.query('ROLLBACK'); return send(res, 409, { error: 'Эта связь создаст цикл' }); }
      const result = await client.query(`INSERT INTO links (source_id,target_id,order_index)
        VALUES ($1,$2,COALESCE((SELECT max(order_index)+1 FROM links WHERE source_id=$1),0))
        ON CONFLICT (source_id,target_id) DO NOTHING RETURNING *`, [input.sourceId, input.targetId]);
      if (result.rowCount) await reconcileSections(client);
      await client.query('COMMIT');
      return result.rowCount ? send(res, 201, mapLink(result.rows[0])) : send(res, 409, { error: 'Связь уже существует' });
    } catch (error) { await client.query('ROLLBACK'); throw error; }
    finally { client.release(); }
  }
  const linkMatch = path.match(/^\/api\/links\/([^/]+)$/);
  if (req.method === 'DELETE' && linkMatch && uuid.test(linkMatch[1])) {
    const client = await pool.connect();
    try {
      await client.query('BEGIN');
      await client.query('SELECT pg_advisory_xact_lock(8675309)');
      const result = await client.query('DELETE FROM links WHERE id=$1', [linkMatch[1]]);
      if (result.rowCount) await reconcileSections(client);
      await client.query('COMMIT');
      return send(res, result.rowCount ? 200 : 404, result.rowCount ? { deleted: true } : { error: 'Связь не найдена' });
    } catch (error) { await client.query('ROLLBACK'); throw error; }
    finally { client.release(); }
  }
  const sectionMatch = path.match(/^\/api\/sections\/([^/]+)$/);
  if (req.method === 'PATCH' && sectionMatch && uuid.test(sectionMatch[1])) {
    const input = await body(req);
    if (!input || typeof input !== 'object' || Array.isArray(input) || typeof input.name !== 'string' || input.name.length > 120) return send(res, 400, { error: 'Название секции должно быть строкой до 120 символов' });
    const result = await pool.query('UPDATE sections SET name=$1 WHERE id=$2 RETURNING *', [input.name.trim() || null, sectionMatch[1]]);
    return result.rowCount ? send(res, 200, mapSection(result.rows[0])) : send(res, 404, { error: 'Секция не найдена' });
  }
  return send(res, 404, { error: 'Маршрут не найден' });
}

async function start() {
  await init();
  http.createServer((req, res) => route(req, res).catch(error => {
    console.error(error);
    send(res, error.code >= 400 && error.code < 500 ? error.code : 500, { error: error.code >= 400 && error.code < 500 ? error.message : 'Ошибка сервера' });
  })).listen(port, '0.0.0.0', () => console.log(`API listening on ${port}`));
}
start().catch(error => { console.error(error); process.exit(1); });
